// <auto-generated />
namespace aegis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class awal23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(awal23));
        
        string IMigrationMetadata.Id
        {
            get { return "201701300830391_awal23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
